version: '3.8'
services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: none
    ports:
      - "5432:5432"

  joule:
    build: .
    links:
      - timescale
    depends_on:
      - timescale
    environment:
      POSTGRES_PASSWORD: password
      HOST: timescale
      PORT: 5432
    privileged: true

